#!/bin/sh
uci -q batch <<'EOI'

# Wireless default settings for radio0 (5 GHz)
set wireless.default_radio0.wnm_sleep_mode='1'
set wireless.default_radio0.ieee80211k='1'
set wireless.default_radio0.time_advertisement='2'
set wireless.default_radio0.bss_transition='1'
set wireless.default_radio0.proxy_arp='1'
set wireless.default_radio0.ocv='1'

# Wireless radio0 specific settings
set wireless.radio0.htmode='HE80'
set wireless.radio0.channel='36'
set wireless.radio0.country='00'

# Wireless default settings for radio1 (2.4 GHz)
set wireless.default_radio1.wnm_sleep_mode='1'
set wireless.default_radio1.ieee80211k='1'
set wireless.default_radio1.time_advertisement='2'
set wireless.default_radio1.bss_transition='1'
set wireless.default_radio1.proxy_arp='1'
set wireless.default_radio1.ocv='1'

# Wireless radio1 specific settings
set wireless.radio1.htmode='HE40'
set wireless.radio1.channel='1'
set wireless.radio1.country='00'

# Firewall settings
set firewall.@zone[1].input='DROP'
set firewall.@zone[1].forward='DROP'
set firewall.@defaults[0].flow_offloading='0'
set firewall.@defaults[0].flow_offloading_hw='0'

# Network settings
set network.globals.packet_steering='0'

# BCP38 settings
set bcp38.@bcp38[0].enabled='1'
set bcp38.@bcp38[0].interface='wan'

# uHTTPd settings
set uhttpd.main.redirect_https='1'

commit wireless
commit firewall
commit network
commit bcp38
commit uhttpd
EOI

exit 0
